from setuptools import setup, Extension

setup_args = dict(
    ext_modules=[
        Extension(
            'toluene_extensions.models.earth.coefficients',
            [
                'toluene/c_extensions/src/models/earth/coefficients.c'
            ],
            include_dirs=['toluene/c_extensions/include'],
            py_limited_api=True
        ),
        Extension(
            'toluene_extensions.models.earth.coordinates',
            [
                'toluene/c_extensions/src/math/linear_algebra.c',
                'toluene/c_extensions/src/models/earth/bias.c',
                'toluene/c_extensions/src/models/earth/coordinates.c',
                'toluene/c_extensions/src/models/earth/earth_orientation.c',
                'toluene/c_extensions/src/models/earth/polar_motion.c',
            ],
            include_dirs=['toluene/c_extensions/include'],
            py_limited_api=True
        ),
        Extension(
            'toluene_extensions.models.earth.earth_orientation',
            [
                'toluene/c_extensions/src/models/earth/earth_orientation.c'
            ],
            include_dirs=['toluene/c_extensions/include'],
            py_limited_api=True
        ),
        Extension(
            'toluene_extensions.models.earth.ellipsoid',
            [
                'toluene/c_extensions/src/models/earth/ellipsoid.c'
            ],
            include_dirs=['toluene/c_extensions/include'],
            py_limited_api=True
        ),
        Extension(
            'toluene_extensions.models.earth.model',
            [
                'toluene/c_extensions/src/models/earth/model.c'
            ],
            include_dirs=['toluene/c_extensions/include'],
            py_limited_api=True
        ),
        Extension(
            'toluene_extensions.util.config',
            [
                'toluene/c_extensions/src/util/config.c'
            ],
            include_dirs=['toluene/c_extensions/include'],
            py_limited_api=True
        ),
    ],
)
setup(**setup_args)
